version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: mongoose
    versions:
    - 5.11.13
    - 5.11.14
    - 5.11.16
    - 5.11.17
    - 5.11.18
    - 5.11.19
    - 5.12.0
    - 5.12.1
    - 5.12.2
    - 5.12.3
    - 5.12.5
  - dependency-name: mongodb
    versions:
    - 3.6.5
  - dependency-name: express-rate-limit
    versions:
    - 5.2.5
